//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResinaSoft_WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTask
    {
        public int Id { get; set; }
        public int PersonelId { get; set; }
        public int TaskId { get; set; }
        public string TaskStatus { get; set; }
    
        public virtual Person Person { private get; set; }
        public virtual Task Task { private get; set; }
    }
}
