//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResinaSoft_WinForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResinaSoftDBContainer : DbContext
    {
        public ResinaSoftDBContainer()
            : base("name=ResinaSoftDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonAddresses> PersonAddresses { get; set; }
        public virtual DbSet<PersonelTask> PersonelTask { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
